} add speed -0.01
{ add speed 0.01
] add speed -0.1
[ add speed 0.1 
k no-osd cycle-values glsl-shaders "~~/shaders/invert.glsl" "" ; show-text "Invert Shader"
alt+a vf toggle negate
alt+b set contrast -35
alt+h cycle-values hwdec auto-safe no ; show-text "HWDEC: ${hwdec}"
alt+i cycle-values interpolation yes no ; show-text "Interp: ${interpolation}"
#s screenshot video
