# Base performance profile for MPV
gpu-context=x11egl
# Use software decoding - avoids AV1 hwdec issues on this system
hwdec=no
gpu-api=opengl
framedrop=vo
video-sync=display-resample
demuxer-thread=yes

# Screenshots: {timestamp} - {video name}
screenshot-template="%F.%P"
