return {

	'sainnhe/sonokai',
	config = function()
		vim.g.sonokai_style = 'andromeda'
		vim.cmd [[colorscheme sonokai]]
		vim.g.sonokai_transparent_background = 2
		vim.cmd [[colorscheme sonokai]]
		vim.cmd [[highlight Normal ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight NormalNC ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight NormalSB ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight EndOfBuffer ctermbg=NONE guibg=NONE]]

		vim.cmd [[highlight BufferDefaultCurrent ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferDefaultCurrentERROR guifg=#BF616A guibg=#252630]]
		vim.cmd [[highlight BufferDefaultCurrentWARN guifg=#EBCB8B guibg=#252630]]
		vim.cmd [[highlight BufferDefaultCurrentHINT guifg=#81A1C1 guibg=#252630]]
		vim.cmd [[highlight BufferCurrentERROR ctermbg=NONE guifg=#BF616A guibg=NONE]]
		vim.cmd [[highlight BufferCurrentHINT ctermbg=NONE guifg=#81A1C1 guibg=NONE]]
		vim.cmd [[highlight BufferCurrentWARN ctermbg=NONE guifg=#81A1C1 guibg=NONE]]
		vim.cmd [[highlight BufferDefaultVisibleERROR ctermbg=NONE guifg=#BF616A guibg=NONE]]
		vim.cmd [[highlight BufferDefaultVisibleHINT ctermbg=NONE guifg=#81A1C1 guibg=NONE]]
		vim.cmd [[highlight BufferDefaultVisibleWARN ctermbg=NONE guifg=#81A1C1 guibg=NONE]]
		vim.cmd [[highlight BufferVisibleERROR ctermbg=NONE guifg=#BF616A guibg=NONE]]
		vim.cmd [[highlight BufferVisibleHINT ctermbg=NONE guifg=#81A1C1 guibg=NONE]]
		vim.cmd [[highlight BufferVisibleWARN ctermbg=NONE guifg=#81A1C1 guibg=NONE]]
		vim.cmd [[highlight BufferDefaultInactiveERROR ctermbg=232 guifg=#BF616A guibg=#252630]]
		vim.cmd [[highlight BufferDefaultInactiveHINT ctermbg=232 guifg=#81A1C1 guibg=#252630]]
		vim.cmd [[highlight BufferDefaultInactiveWARN ctermbg=232 guifg=#81A1C1 guibg=#252630]]
		vim.cmd [[highlight BufferInactiveERROR ctermbg=232 guifg=#BF616A guibg=#252630]]
		vim.cmd [[highlight BufferInactiveHINT ctermbg=232 guifg=#81A1C1 guibg=#252630]]
		vim.cmd [[highlight BufferInactiveWARN ctermbg=232 guifg=#81A1C1 guibg=#252630]]
		vim.cmd [[highlight BufferCurrent ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentADDED ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentBtn ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentCHANGED ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentDELETED ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentIcon ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentIndex ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentINFO ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentMod ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentModBtn ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentNumber ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentPin ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentPinBtn ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentSign ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentSignRight ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferCurrentTarget ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisible ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleADDED ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleBtn ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleCHANGED ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleDELETED ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleERROR ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleHINT ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleIcon ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleIndex ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleINFO ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleMod ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleModBtn ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleNumber ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisiblePin ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisiblePinBtn ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleSign ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleSignRight ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleTarget ctermbg=NONE guibg=NONE]]
		vim.cmd [[highlight BufferVisibleWARN ctermbg=NONE guibg=NONE]]
	end
}
