# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
	config,
	lib,
	pkgs,
	modulesPath,
	...
}: {
	imports = [
		(modulesPath + "/installer/scan/not-detected.nix")
	];

	boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "rtsx_pci_sdmmc"];
	boot.initrd.kernelModules = [];
	boot.kernelModules = ["kvm-amd" "kvm-intel"];
	boot.kernelParams = ["acpi_backlight=video"];
	boot.extraModulePackages = [];

	fileSystems."/" = {
		device = "/dev/disk/by-uuid/27b12386-cf3d-414a-9637-81970723cc22";
		fsType = "ext4";
	};

	fileSystems."/boot" = {
		device = "/dev/disk/by-uuid/4207-2692";
		fsType = "vfat";
		options = ["fmask=0077" "dmask=0077"];
	};

	fileSystems."/home" = {
		device = "/dev/disk/by-uuid/aeddb84b-5f75-4564-8ba8-7962aea05a9b";
		fsType = "ext4";
	};

	swapDevices = [
		{device = "/dev/disk/by-uuid/e9d8369b-b420-4ae1-a56b-e64b5cf04e85";}
	];

	networking.useDHCP = lib.mkDefault true;
	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
