# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
	config,
	lib,
	pkgs,
	...
}: {
	hardware.graphics = {
		enable = true;
	};
	services.xserver.videoDrivers = ["modesetting" "nvidia"];
	hardware.nvidia = {
		modesetting.enable = true;
		nvidiaSettings = true;
		open=false;
		package = config.boot.kernelPackages.nvidiaPackages.stable;
	};
	hardware.nvidia.prime = {
		sync.enable = true;

		intelBusId = "PCI:0:2:0";
		nvidiaBusId = "PCI:1:0:0";
	};
}
