{...}: {
	imports = [
		./cli.nix
		./lf.nix
		./dev/core.nix
		./dev/js.nix
		./dev/python.nix
		./dev/rust.nix
		./dev/go.nix
		./dev/dotnet.nix
		./dev/jvm.nix
		./dev/android.nix
		./dev/cpp.nix
		./dev/lua.nix
		./dev/db.nix
		./dev/docker.nix
		./dev/http.nix
		./dev/web.nix
		./dev/infra.nix
		./dev/fun.nix
		./gaming.nix
		./media.nix
		./security.nix
		./latex.nix
		./chat.nix
		./browsers.nix
		./desktop.nix
		./apps.nix
		./apps/winapps.nix
		./theme.nix
		./spicetify.nix
		./secrets.nix
		./git.nix
		./neovim.nix
		./xdg.nix
		./kdeconnect.nix
		./shell.nix
		# CLI / TUI tools
		./tmux.nix
		./btop.nix
		./mpv.nix
		./zathura.nix
		./newsboat.nix
		./wezterm.nix
		# Desktop / WM
		./rofi.nix
		./bspwm.nix
		./sxhkd.nix
		./polybar.nix
		./wm-x11.nix
	];
}
